version: '3'

networks:
  tincho:
    driver: bridge

services:
  tincho-svc:
    image: nginx:alpine
    restart: on-failure
    volumes:
      - ./rootfs/tincho:/usr/share/nginx/html
    networks:
      - tincho

  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    links:
      - tincho-svc
    volumes:
      - ./rootfs/config:/config
    environment:
      # - PGID:<gid>
      # - PUID:<uid> 
      - URL
      - SUBDOMAINS
      - VALIDATION
      - STAGING
      - TZ
      - EMAIL
    networks: 
      - tincho
    ports:
      - "443:443"
      - "80:80"
