version: '3'

networks:
  tincho:
    driver: bridge

services:
  tincho-svc:
    image: nginx:alpine
    restart: on-failure
    networks:
      - tincho

  letsencrypt:
    image: linuxserver/letsencrypt
    volumes:
      - ./rootfs:/
      - letsencrypt_config:/config
      - letsencrypt_certs:/config/etc/letsencrypt
    environment:
      # - PGID:<gid>
      # - PUID:<uid> 
      - URL
      - SUBDOMAINS
      - VALIDATION
      - TZ
      - EMAIL
    networks: 
      - tincho
    ports:
      - "443:443"
      - "80:80"

volumes:
  letsencrypt_certs: ~
  letsencrypt_config: ~